export const sampleData = {
  "total_count": 2382,
  "incomplete_results": false,
  "items": [
    {
      "login": "wael",
      "id": 14587,
      "node_id": "MDQ6VXNlcjE0NTg3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/14587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wael",
      "html_url": "https://github.com/wael",
      "followers_url": "https://api.github.com/users/wael/followers",
      "following_url": "https://api.github.com/users/wael/following{/other_user}",
      "gists_url": "https://api.github.com/users/wael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wael/subscriptions",
      "organizations_url": "https://api.github.com/users/wael/orgs",
      "repos_url": "https://api.github.com/users/wael/repos",
      "events_url": "https://api.github.com/users/wael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "kalbasit",
      "id": 87115,
      "node_id": "MDQ6VXNlcjg3MTE1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/87115?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kalbasit",
      "html_url": "https://github.com/kalbasit",
      "followers_url": "https://api.github.com/users/kalbasit/followers",
      "following_url": "https://api.github.com/users/kalbasit/following{/other_user}",
      "gists_url": "https://api.github.com/users/kalbasit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kalbasit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kalbasit/subscriptions",
      "organizations_url": "https://api.github.com/users/kalbasit/orgs",
      "repos_url": "https://api.github.com/users/kalbasit/repos",
      "events_url": "https://api.github.com/users/kalbasit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kalbasit/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wael93",
      "id": 10253564,
      "node_id": "MDQ6VXNlcjEwMjUzNTY0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/10253564?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wael93",
      "html_url": "https://github.com/wael93",
      "followers_url": "https://api.github.com/users/wael93/followers",
      "following_url": "https://api.github.com/users/wael93/following{/other_user}",
      "gists_url": "https://api.github.com/users/wael93/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wael93/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wael93/subscriptions",
      "organizations_url": "https://api.github.com/users/wael93/orgs",
      "repos_url": "https://api.github.com/users/wael93/repos",
      "events_url": "https://api.github.com/users/wael93/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wael93/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waelalameen",
      "id": 29306627,
      "node_id": "MDQ6VXNlcjI5MzA2NjI3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/29306627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waelalameen",
      "html_url": "https://github.com/waelalameen",
      "followers_url": "https://api.github.com/users/waelalameen/followers",
      "following_url": "https://api.github.com/users/waelalameen/following{/other_user}",
      "gists_url": "https://api.github.com/users/waelalameen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waelalameen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waelalameen/subscriptions",
      "organizations_url": "https://api.github.com/users/waelalameen/orgs",
      "repos_url": "https://api.github.com/users/waelalameen/repos",
      "events_url": "https://api.github.com/users/waelalameen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waelalameen/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "elhachimi",
      "id": 3928471,
      "node_id": "MDQ6VXNlcjM5Mjg0NzE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3928471?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elhachimi",
      "html_url": "https://github.com/elhachimi",
      "followers_url": "https://api.github.com/users/elhachimi/followers",
      "following_url": "https://api.github.com/users/elhachimi/following{/other_user}",
      "gists_url": "https://api.github.com/users/elhachimi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elhachimi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elhachimi/subscriptions",
      "organizations_url": "https://api.github.com/users/elhachimi/orgs",
      "repos_url": "https://api.github.com/users/elhachimi/repos",
      "events_url": "https://api.github.com/users/elhachimi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elhachimi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waelsy123",
      "id": 1936754,
      "node_id": "MDQ6VXNlcjE5MzY3NTQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1936754?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waelsy123",
      "html_url": "https://github.com/waelsy123",
      "followers_url": "https://api.github.com/users/waelsy123/followers",
      "following_url": "https://api.github.com/users/waelsy123/following{/other_user}",
      "gists_url": "https://api.github.com/users/waelsy123/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waelsy123/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waelsy123/subscriptions",
      "organizations_url": "https://api.github.com/users/waelsy123/orgs",
      "repos_url": "https://api.github.com/users/waelsy123/repos",
      "events_url": "https://api.github.com/users/waelsy123/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waelsy123/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waelkdouh",
      "id": 10424576,
      "node_id": "MDQ6VXNlcjEwNDI0NTc2",
      "avatar_url": "https://avatars2.githubusercontent.com/u/10424576?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waelkdouh",
      "html_url": "https://github.com/waelkdouh",
      "followers_url": "https://api.github.com/users/waelkdouh/followers",
      "following_url": "https://api.github.com/users/waelkdouh/following{/other_user}",
      "gists_url": "https://api.github.com/users/waelkdouh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waelkdouh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waelkdouh/subscriptions",
      "organizations_url": "https://api.github.com/users/waelkdouh/orgs",
      "repos_url": "https://api.github.com/users/waelkdouh/repos",
      "events_url": "https://api.github.com/users/waelkdouh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waelkdouh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "WaelHamze",
      "id": 11046518,
      "node_id": "MDQ6VXNlcjExMDQ2NTE4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/11046518?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WaelHamze",
      "html_url": "https://github.com/WaelHamze",
      "followers_url": "https://api.github.com/users/WaelHamze/followers",
      "following_url": "https://api.github.com/users/WaelHamze/following{/other_user}",
      "gists_url": "https://api.github.com/users/WaelHamze/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WaelHamze/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WaelHamze/subscriptions",
      "organizations_url": "https://api.github.com/users/WaelHamze/orgs",
      "repos_url": "https://api.github.com/users/WaelHamze/repos",
      "events_url": "https://api.github.com/users/WaelHamze/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WaelHamze/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MohamedWael",
      "id": 6018761,
      "node_id": "MDQ6VXNlcjYwMTg3NjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6018761?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MohamedWael",
      "html_url": "https://github.com/MohamedWael",
      "followers_url": "https://api.github.com/users/MohamedWael/followers",
      "following_url": "https://api.github.com/users/MohamedWael/following{/other_user}",
      "gists_url": "https://api.github.com/users/MohamedWael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MohamedWael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MohamedWael/subscriptions",
      "organizations_url": "https://api.github.com/users/MohamedWael/orgs",
      "repos_url": "https://api.github.com/users/MohamedWael/repos",
      "events_url": "https://api.github.com/users/MohamedWael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MohamedWael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waeljammal",
      "id": 140032,
      "node_id": "MDQ6VXNlcjE0MDAzMg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/140032?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waeljammal",
      "html_url": "https://github.com/waeljammal",
      "followers_url": "https://api.github.com/users/waeljammal/followers",
      "following_url": "https://api.github.com/users/waeljammal/following{/other_user}",
      "gists_url": "https://api.github.com/users/waeljammal/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waeljammal/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waeljammal/subscriptions",
      "organizations_url": "https://api.github.com/users/waeljammal/orgs",
      "repos_url": "https://api.github.com/users/waeljammal/repos",
      "events_url": "https://api.github.com/users/waeljammal/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waeljammal/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wael-mohamed",
      "id": 24360200,
      "node_id": "MDQ6VXNlcjI0MzYwMjAw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/24360200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wael-mohamed",
      "html_url": "https://github.com/wael-mohamed",
      "followers_url": "https://api.github.com/users/wael-mohamed/followers",
      "following_url": "https://api.github.com/users/wael-mohamed/following{/other_user}",
      "gists_url": "https://api.github.com/users/wael-mohamed/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wael-mohamed/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wael-mohamed/subscriptions",
      "organizations_url": "https://api.github.com/users/wael-mohamed/orgs",
      "repos_url": "https://api.github.com/users/wael-mohamed/repos",
      "events_url": "https://api.github.com/users/wael-mohamed/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wael-mohamed/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "forzagreen",
      "id": 8544289,
      "node_id": "MDQ6VXNlcjg1NDQyODk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8544289?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/forzagreen",
      "html_url": "https://github.com/forzagreen",
      "followers_url": "https://api.github.com/users/forzagreen/followers",
      "following_url": "https://api.github.com/users/forzagreen/following{/other_user}",
      "gists_url": "https://api.github.com/users/forzagreen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/forzagreen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/forzagreen/subscriptions",
      "organizations_url": "https://api.github.com/users/forzagreen/orgs",
      "repos_url": "https://api.github.com/users/forzagreen/repos",
      "events_url": "https://api.github.com/users/forzagreen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/forzagreen/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "OmarBazaraa",
      "id": 6713329,
      "node_id": "MDQ6VXNlcjY3MTMzMjk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6713329?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/OmarBazaraa",
      "html_url": "https://github.com/OmarBazaraa",
      "followers_url": "https://api.github.com/users/OmarBazaraa/followers",
      "following_url": "https://api.github.com/users/OmarBazaraa/following{/other_user}",
      "gists_url": "https://api.github.com/users/OmarBazaraa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/OmarBazaraa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/OmarBazaraa/subscriptions",
      "organizations_url": "https://api.github.com/users/OmarBazaraa/orgs",
      "repos_url": "https://api.github.com/users/OmarBazaraa/repos",
      "events_url": "https://api.github.com/users/OmarBazaraa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/OmarBazaraa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Waelazar",
      "id": 24638670,
      "node_id": "MDQ6VXNlcjI0NjM4Njcw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/24638670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Waelazar",
      "html_url": "https://github.com/Waelazar",
      "followers_url": "https://api.github.com/users/Waelazar/followers",
      "following_url": "https://api.github.com/users/Waelazar/following{/other_user}",
      "gists_url": "https://api.github.com/users/Waelazar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Waelazar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Waelazar/subscriptions",
      "organizations_url": "https://api.github.com/users/Waelazar/orgs",
      "repos_url": "https://api.github.com/users/Waelazar/repos",
      "events_url": "https://api.github.com/users/Waelazar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Waelazar/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "WaelLoop",
      "id": 26651744,
      "node_id": "MDQ6VXNlcjI2NjUxNzQ0",
      "avatar_url": "https://avatars2.githubusercontent.com/u/26651744?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WaelLoop",
      "html_url": "https://github.com/WaelLoop",
      "followers_url": "https://api.github.com/users/WaelLoop/followers",
      "following_url": "https://api.github.com/users/WaelLoop/following{/other_user}",
      "gists_url": "https://api.github.com/users/WaelLoop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WaelLoop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WaelLoop/subscriptions",
      "organizations_url": "https://api.github.com/users/WaelLoop/orgs",
      "repos_url": "https://api.github.com/users/WaelLoop/repos",
      "events_url": "https://api.github.com/users/WaelLoop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WaelLoop/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wael34218",
      "id": 334876,
      "node_id": "MDQ6VXNlcjMzNDg3Ng==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/334876?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wael34218",
      "html_url": "https://github.com/wael34218",
      "followers_url": "https://api.github.com/users/wael34218/followers",
      "following_url": "https://api.github.com/users/wael34218/following{/other_user}",
      "gists_url": "https://api.github.com/users/wael34218/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wael34218/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wael34218/subscriptions",
      "organizations_url": "https://api.github.com/users/wael34218/orgs",
      "repos_url": "https://api.github.com/users/wael34218/repos",
      "events_url": "https://api.github.com/users/wael34218/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wael34218/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waellomari",
      "id": 61183681,
      "node_id": "MDQ6VXNlcjYxMTgzNjgx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/61183681?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waellomari",
      "html_url": "https://github.com/waellomari",
      "followers_url": "https://api.github.com/users/waellomari/followers",
      "following_url": "https://api.github.com/users/waellomari/following{/other_user}",
      "gists_url": "https://api.github.com/users/waellomari/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waellomari/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waellomari/subscriptions",
      "organizations_url": "https://api.github.com/users/waellomari/orgs",
      "repos_url": "https://api.github.com/users/waellomari/repos",
      "events_url": "https://api.github.com/users/waellomari/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waellomari/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waelchateur",
      "id": 23665062,
      "node_id": "MDQ6VXNlcjIzNjY1MDYy",
      "avatar_url": "https://avatars2.githubusercontent.com/u/23665062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waelchateur",
      "html_url": "https://github.com/waelchateur",
      "followers_url": "https://api.github.com/users/waelchateur/followers",
      "following_url": "https://api.github.com/users/waelchateur/following{/other_user}",
      "gists_url": "https://api.github.com/users/waelchateur/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waelchateur/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waelchateur/subscriptions",
      "organizations_url": "https://api.github.com/users/waelchateur/orgs",
      "repos_url": "https://api.github.com/users/waelchateur/repos",
      "events_url": "https://api.github.com/users/waelchateur/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waelchateur/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "WaelAshraf",
      "id": 41231084,
      "node_id": "MDQ6VXNlcjQxMjMxMDg0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/41231084?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WaelAshraf",
      "html_url": "https://github.com/WaelAshraf",
      "followers_url": "https://api.github.com/users/WaelAshraf/followers",
      "following_url": "https://api.github.com/users/WaelAshraf/following{/other_user}",
      "gists_url": "https://api.github.com/users/WaelAshraf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WaelAshraf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WaelAshraf/subscriptions",
      "organizations_url": "https://api.github.com/users/WaelAshraf/orgs",
      "repos_url": "https://api.github.com/users/WaelAshraf/repos",
      "events_url": "https://api.github.com/users/WaelAshraf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WaelAshraf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Waelahmed99",
      "id": 45833151,
      "node_id": "MDQ6VXNlcjQ1ODMzMTUx",
      "avatar_url": "https://avatars0.githubusercontent.com/u/45833151?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Waelahmed99",
      "html_url": "https://github.com/Waelahmed99",
      "followers_url": "https://api.github.com/users/Waelahmed99/followers",
      "following_url": "https://api.github.com/users/Waelahmed99/following{/other_user}",
      "gists_url": "https://api.github.com/users/Waelahmed99/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Waelahmed99/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Waelahmed99/subscriptions",
      "organizations_url": "https://api.github.com/users/Waelahmed99/orgs",
      "repos_url": "https://api.github.com/users/Waelahmed99/repos",
      "events_url": "https://api.github.com/users/Waelahmed99/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Waelahmed99/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wnafee",
      "id": 352685,
      "node_id": "MDQ6VXNlcjM1MjY4NQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/352685?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wnafee",
      "html_url": "https://github.com/wnafee",
      "followers_url": "https://api.github.com/users/wnafee/followers",
      "following_url": "https://api.github.com/users/wnafee/following{/other_user}",
      "gists_url": "https://api.github.com/users/wnafee/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wnafee/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wnafee/subscriptions",
      "organizations_url": "https://api.github.com/users/wnafee/orgs",
      "repos_url": "https://api.github.com/users/wnafee/repos",
      "events_url": "https://api.github.com/users/wnafee/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wnafee/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "WaelFa",
      "id": 43610877,
      "node_id": "MDQ6VXNlcjQzNjEwODc3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/43610877?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WaelFa",
      "html_url": "https://github.com/WaelFa",
      "followers_url": "https://api.github.com/users/WaelFa/followers",
      "following_url": "https://api.github.com/users/WaelFa/following{/other_user}",
      "gists_url": "https://api.github.com/users/WaelFa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WaelFa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WaelFa/subscriptions",
      "organizations_url": "https://api.github.com/users/WaelFa/orgs",
      "repos_url": "https://api.github.com/users/WaelFa/repos",
      "events_url": "https://api.github.com/users/WaelFa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WaelFa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "waelaniba",
      "id": 3081253,
      "node_id": "MDQ6VXNlcjMwODEyNTM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3081253?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/waelaniba",
      "html_url": "https://github.com/waelaniba",
      "followers_url": "https://api.github.com/users/waelaniba/followers",
      "following_url": "https://api.github.com/users/waelaniba/following{/other_user}",
      "gists_url": "https://api.github.com/users/waelaniba/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/waelaniba/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/waelaniba/subscriptions",
      "organizations_url": "https://api.github.com/users/waelaniba/orgs",
      "repos_url": "https://api.github.com/users/waelaniba/repos",
      "events_url": "https://api.github.com/users/waelaniba/events{/privacy}",
      "received_events_url": "https://api.github.com/users/waelaniba/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Mr-Wii",
      "id": 7716664,
      "node_id": "MDQ6VXNlcjc3MTY2NjQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7716664?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Mr-Wii",
      "html_url": "https://github.com/Mr-Wii",
      "followers_url": "https://api.github.com/users/Mr-Wii/followers",
      "following_url": "https://api.github.com/users/Mr-Wii/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mr-Wii/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mr-Wii/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mr-Wii/subscriptions",
      "organizations_url": "https://api.github.com/users/Mr-Wii/orgs",
      "repos_url": "https://api.github.com/users/Mr-Wii/repos",
      "events_url": "https://api.github.com/users/Mr-Wii/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mr-Wii/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thelordhitman",
      "id": 1159518,
      "node_id": "MDQ6VXNlcjExNTk1MTg=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1159518?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thelordhitman",
      "html_url": "https://github.com/thelordhitman",
      "followers_url": "https://api.github.com/users/thelordhitman/followers",
      "following_url": "https://api.github.com/users/thelordhitman/following{/other_user}",
      "gists_url": "https://api.github.com/users/thelordhitman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thelordhitman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thelordhitman/subscriptions",
      "organizations_url": "https://api.github.com/users/thelordhitman/orgs",
      "repos_url": "https://api.github.com/users/thelordhitman/repos",
      "events_url": "https://api.github.com/users/thelordhitman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thelordhitman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eloraiby",
      "id": 1127262,
      "node_id": "MDQ6VXNlcjExMjcyNjI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1127262?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eloraiby",
      "html_url": "https://github.com/eloraiby",
      "followers_url": "https://api.github.com/users/eloraiby/followers",
      "following_url": "https://api.github.com/users/eloraiby/following{/other_user}",
      "gists_url": "https://api.github.com/users/eloraiby/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eloraiby/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eloraiby/subscriptions",
      "organizations_url": "https://api.github.com/users/eloraiby/orgs",
      "repos_url": "https://api.github.com/users/eloraiby/repos",
      "events_url": "https://api.github.com/users/eloraiby/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eloraiby/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Kayoti",
      "id": 3899197,
      "node_id": "MDQ6VXNlcjM4OTkxOTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3899197?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Kayoti",
      "html_url": "https://github.com/Kayoti",
      "followers_url": "https://api.github.com/users/Kayoti/followers",
      "following_url": "https://api.github.com/users/Kayoti/following{/other_user}",
      "gists_url": "https://api.github.com/users/Kayoti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Kayoti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Kayoti/subscriptions",
      "organizations_url": "https://api.github.com/users/Kayoti/orgs",
      "repos_url": "https://api.github.com/users/Kayoti/repos",
      "events_url": "https://api.github.com/users/Kayoti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Kayoti/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ahmedwael19",
      "id": 27695042,
      "node_id": "MDQ6VXNlcjI3Njk1MDQy",
      "avatar_url": "https://avatars2.githubusercontent.com/u/27695042?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ahmedwael19",
      "html_url": "https://github.com/ahmedwael19",
      "followers_url": "https://api.github.com/users/ahmedwael19/followers",
      "following_url": "https://api.github.com/users/ahmedwael19/following{/other_user}",
      "gists_url": "https://api.github.com/users/ahmedwael19/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ahmedwael19/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ahmedwael19/subscriptions",
      "organizations_url": "https://api.github.com/users/ahmedwael19/orgs",
      "repos_url": "https://api.github.com/users/ahmedwael19/repos",
      "events_url": "https://api.github.com/users/ahmedwael19/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ahmedwael19/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "btwael",
      "id": 1284701,
      "node_id": "MDQ6VXNlcjEyODQ3MDE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1284701?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/btwael",
      "html_url": "https://github.com/btwael",
      "followers_url": "https://api.github.com/users/btwael/followers",
      "following_url": "https://api.github.com/users/btwael/following{/other_user}",
      "gists_url": "https://api.github.com/users/btwael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/btwael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/btwael/subscriptions",
      "organizations_url": "https://api.github.com/users/btwael/orgs",
      "repos_url": "https://api.github.com/users/btwael/repos",
      "events_url": "https://api.github.com/users/btwael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/btwael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "w43l",
      "id": 43235,
      "node_id": "MDQ6VXNlcjQzMjM1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/43235?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/w43l",
      "html_url": "https://github.com/w43l",
      "followers_url": "https://api.github.com/users/w43l/followers",
      "following_url": "https://api.github.com/users/w43l/following{/other_user}",
      "gists_url": "https://api.github.com/users/w43l/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/w43l/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/w43l/subscriptions",
      "organizations_url": "https://api.github.com/users/w43l/orgs",
      "repos_url": "https://api.github.com/users/w43l/repos",
      "events_url": "https://api.github.com/users/w43l/events{/privacy}",
      "received_events_url": "https://api.github.com/users/w43l/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
};


export default sampleData;
